name: pogo-env
channels:
  - bpteague
  - defaults
dependencies:
  - conda
  - python=3.9
  - python.app
  - notebook=6.3.0
  - biopython
  - ipykernel=5.5.3
  - seaborn=0.13.2
  - pandas=2.2.3
  - numpy=2.0.2
  - pysam=0.23.0
  - matplotlib=3.9.4